# 简化分块文本清洗Pipeline配置
# 基于UltraRAG框架的文本分块处理方案

servers:
  custom: servers/custom

variables:
  # 输入文件路径
  input_file: "test_large_text.txt"
  # 输出文件路径
  output_file: "data/test_large_cleaned_simple_chunked.txt"
  # 分块大小（字符数）
  chunk_size: 1000
  # 分块重叠大小
  chunk_overlap: 150

pipeline:
  # 1. 加载文本文件
  - custom.load_text_file:
      input:
        file_path: $input_file
      output:
        text_content: text_content
  
  # 2. 文本分块处理
  - custom.chunk_text:
      input:
        text_content: text_content
        chunk_size: $chunk_size
        chunk_overlap: $chunk_overlap
      output:
        text_chunks: text_chunks
  
  # 3. 基础清洗文本块
  - custom.clean_text_chunks:
      input:
        chunks: text_chunks
      output:
        cleaned_chunks: cleaned_chunks
  
  # 4. 合并清洗后的文本块
  - custom.merge_cleaned_chunks:
      input:
        cleaned_chunks: cleaned_chunks
      output:
        merged_text: merged_text
  
  # 5. 保存清洗后的文本
  - custom.save_cleaned_text:
      input:
        merged_text: merged_text
        output_path: $output_file